baseURL: "https://netanyawilliams.github.io" 
title: Netanya Williams
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: About Me
          url: books/
          weight: 5 
        - name: Research
          url: papers/
          weight: 2
        - name: Data
          url: data/
          weight: 4 

params:
    description: "I am a MS student in the UConn EEB department interested in Parasite imaging and phylogenetics. Parasitic copepod taxonomy, systematics, and host association."
    author: Netanya Williams
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Netanya Williams
          subtitle: "I am a MS student in the UConn EEB department interested in Parasite imaging and phylogenetics. Parasitic copepod taxonomy, systematics, and host association. Add more details of this is the bio area"
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Netanya Williams
          buttons:
            - name: About Me
              url: books/
            - name: Research
              url: papers/
            - name: Data
              url: data/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:netanya.williams@uconn.edu
        - name: Location
          url: location/
        - name: GitHub
          url: https://github.com/pmichaillat
        - name: Twitter
          url: https://twitter.com/NetanyaAW

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Netanya Williams"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
